9614652:  # Date Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Date Annotator
  submit_to:
    - "9614719"  # MCW
  center: SAGEBIO
  # test: false
  # goldstandard: null
9614654:  # Date Annotator - Test
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Date Annotator
  submit_to:
    - "9614719"  # MCW
    - "9614757"  # SAGEBIO Test
  center: SAGEBIO
  # test: true
  # goldstandard: null
9614657:  # Person Name Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Person Name Annotator
  submit_to:
    - "9614720"  # MCW
  center: SAGEBIO
  # test: false
  # goldstandard: null
9614685:  # Person Name Annotator - Test
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Person Name Annotator
  submit_to:
    - "9614720"  # MCW
  center: SAGEBIO
  # test: true
  # goldstandard: null
9614658:  # Physical Address Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to:
    - "9614721"  # MCW
  center: SAGEBIO
  # test: false
  # goldstandard: null
9614684: # Physical Address Annotator - Test
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to:
    - "9614721"  # MCW
  center: SAGEBIO
  # test: true
  # goldstandard: null
9614719: # MCW - Date Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Date Annotator
  submit_to: null
  center: SAGEBIO
  # test: false
  # goldstandard: null
9614757: # SAGEBIO - Date Annotator Test
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Date Annotator
  submit_to: null
  center: SAGEBIO
  # test: false
  # goldstandard: null
9614720: # MCW - Person Name Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Person Name Annotator
  submit_to: null
  center: MCW
  # test: false
  # goldstandard: null
9614721: # MCW - Physical Address Annotator
  dataset_name: 2014-i2b2
  dataset_version: "20201203"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to: null
  center: MCW
  # test: false
  # goldstandard: null